# Generated by Django 5.2.10 on 2026-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفصل')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفصل')),
                ('grade', models.IntegerField(choices=[(1, 'الصف الأول الثانوي'), (2, 'الصف الثاني الثانوي'), (3, 'الصف الثالث الثانوي')], verbose_name='السنة الدراسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chapters/', verbose_name='صورة الفصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['grade', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='نسبة المشاهدة %')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحاضرة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المحاضرة')),
                ('video_url', models.URLField(help_text='ضع رابط الفيديو من Vimeo أو YouTube', verbose_name='رابط الفيديو (Vimeo/YouTube)')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='مدة الفيديو (بالدقائق)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lectures_pdfs/', verbose_name='ملف الملزمة (PDF)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='السعر (جنيه)')),
                ('is_free', models.BooleanField(default=False, verbose_name='مجانية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
                'ordering': ['chapter', 'order'],
            },
        ),
    ]
