# Generated by Django 5.2.10 on 2026-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/', verbose_name='صورة المحاضرة'),
        ),
    ]
