# Generated by Django 5.2.10 on 2026-01-19 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_lecture_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FawryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(help_text='كود التاجر من فوري', max_length=50, verbose_name='كود التاجر (Merchant Code)')),
                ('security_key', models.CharField(help_text='مفتاح الأمان السري من فوري', max_length=100, verbose_name='مفتاح الأمان (Security Key)')),
                ('is_sandbox', models.BooleanField(default=True, help_text='فعّل هذا للاختبار، أوقفه للإنتاج', verbose_name='وضع الاختبار (Sandbox)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات فوري',
                'verbose_name_plural': 'إعدادات فوري',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ (جنيه)')),
                ('payment_method', models.CharField(choices=[('fawry', 'فوري'), ('code', 'كود تفعيل')], default='fawry', max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'تم الدفع'), ('failed', 'فشل'), ('expired', 'منتهي'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('fawry_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم مرجع فوري')),
                ('payment_expiry', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='courses.lecture', verbose_name='المحاضرة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب دفع',
                'verbose_name_plural': 'طلبات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
