# Generated by Django 5.2.10 on 2026-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('etisalat', 'اتصالات كاش'), ('vodafone', 'فودافون كاش'), ('orange', 'أورانج كاش'), ('we', 'وي باي')], default='etisalat', max_length=20, verbose_name='نوع المحفظة')),
                ('wallet_number', models.CharField(help_text='رقم الموبايل المسجل عليه المحفظة', max_length=15, verbose_name='رقم المحفظة')),
                ('wallet_name', models.CharField(help_text='الاسم كما هو مسجل في المحفظة', max_length=100, verbose_name='اسم صاحب المحفظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إعدادات المحفظة',
                'verbose_name_plural': 'إعدادات المحفظة',
            },
        ),
        migrations.DeleteModel(
            name='FawryConfig',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='fawry_ref_number',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment_expiry',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='ملاحظات داخلية', verbose_name='ملاحظات الأدمن'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='الكود المرجعي'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='student_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الطالب'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'محفظة إلكترونية'), ('fawry', 'فوري'), ('code', 'كود تفعيل')], default='wallet', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'تم الدفع ✅'), ('failed', 'فشل'), ('expired', 'منتهي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
