# Generated by Django 5.2.10 on 2026-01-19 09:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة مصرية صحيحة (01xxxxxxxxx)', regex='^01[0125][0-9]{8}$')], verbose_name='رقم الهاتف')),
                ('parent_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة مصرية صحيحة (01xxxxxxxxx)', regex='^01[0125][0-9]{8}$')], verbose_name='رقم ولي الأمر')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('teacher', 'مدرس'), ('admin', 'أدمن')], default='student', max_length=10, verbose_name='الدور')),
                ('grade', models.IntegerField(blank=True, choices=[(1, 'الصف الأول الثانوي'), (2, 'الصف الثاني الثانوي'), (3, 'الصف الثالث الثانوي')], null=True, verbose_name='السنة الدراسية')),
                ('governorate', models.CharField(blank=True, choices=[('cairo', 'القاهرة'), ('giza', 'الجيزة'), ('alexandria', 'الإسكندرية'), ('dakahlia', 'الدقهلية'), ('sharqia', 'الشرقية'), ('qalyubia', 'القليوبية'), ('gharbia', 'الغربية'), ('monufia', 'المنوفية'), ('beheira', 'البحيرة'), ('kafr_el_sheikh', 'كفر الشيخ'), ('damietta', 'دمياط'), ('port_said', 'بورسعيد'), ('ismailia', 'الإسماعيلية'), ('suez', 'السويس'), ('fayoum', 'الفيوم'), ('beni_suef', 'بني سويف'), ('minya', 'المنيا'), ('asyut', 'أسيوط'), ('sohag', 'سوهاج'), ('qena', 'قنا'), ('aswan', 'أسوان'), ('luxor', 'الأقصر'), ('red_sea', 'البحر الأحمر'), ('new_valley', 'الوادي الجديد'), ('matruh', 'مطروح'), ('north_sinai', 'شمال سيناء'), ('south_sinai', 'جنوب سيناء')], max_length=20, verbose_name='المحافظة')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي')),
                ('battery_level', models.IntegerField(default=0, help_text='مستوى تقدم الطالب (0-100)', verbose_name='مستوى الشحن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='الكود')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture', verbose_name='المحاضرة')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مستخدم بواسطة')),
            ],
            options={
                'verbose_name': 'كود تفعيل',
                'verbose_name_plural': 'أكواد التفعيل',
            },
        ),
    ]
