# Generated by Django 5.2.10 on 2026-01-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, verbose_name='تعليمات الامتحان')),
                ('time_limit', models.PositiveIntegerField(default=15, verbose_name='الوقت المسموح (بالدقائق)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='درجة النجاح (%)')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='ترتيب عشوائي للأسئلة')),
                ('show_answers', models.BooleanField(default=True, verbose_name='عرض الإجابات بعد الامتحان')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='عدد المحاولات المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lecture', verbose_name='المحاضرة')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('image', models.ImageField(blank=True, help_text='صورة اختيارية للسؤال (معادلات، رسومات...)', null=True, upload_to='questions/', verbose_name='صورة السؤال')),
                ('option_a', models.CharField(max_length=500, verbose_name='الخيار أ')),
                ('option_b', models.CharField(max_length=500, verbose_name='الخيار ب')),
                ('option_c', models.CharField(max_length=500, verbose_name='الخيار ج')),
                ('option_d', models.CharField(max_length=500, verbose_name='الخيار د')),
                ('correct_answer', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, help_text='يظهر للطالب بعد الامتحان', verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='الدرجة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.quiz', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='الدرجة')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة المئوية')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('answers_data', models.JSONField(blank=True, default=dict, help_text='تخزين إجابات الطالب', verbose_name='بيانات الإجابات')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='الوقت المستغرق (بالثواني)')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='رقم المحاولة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.quiz', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'نتيجة',
                'verbose_name_plural': 'النتائج',
                'ordering': ['-completed_at'],
            },
        ),
    ]
