# Generated by Django 5.2.10 on 2026-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, default='أ', max_length=500, verbose_name='الخيار أ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, default='ب', max_length=500, verbose_name='الخيار ب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, default='ج', max_length=500, verbose_name='الخيار ج'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, default='د', max_length=500, verbose_name='الخيار د'),
        ),
    ]
